/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.GerenciadorDados;
import static view.TelaInicial.caminho;

/**
 *
 * @author João Pedro
 */
public class CriarPlanilhaUI extends javax.swing.JDialog {

    /**
     * Creates new form CriarPlanilhaUI
     */
    public CriarPlanilhaUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLErro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTfCaminho = new javax.swing.JTextField();
        jBtnConcluir = new javax.swing.JButton();
        jBtnCriarPlanilha = new javax.swing.JButton();
        jBtnCopiar = new javax.swing.JButton();
        jLCopiado = new javax.swing.JLabel();

        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\Users\\João Pedro\\Downloads"));
        jFileChooser1.setDialogTitle("");
        jFileChooser1.setFileHidingEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLErro.setForeground(new java.awt.Color(204, 0, 0));

        jLabel1.setText("Criar planilha");

        jLabel2.setText("Diretório da planilha:");

        jButton1.setText("Procurar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTfCaminho.setEditable(false);
        jTfCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfCaminhoActionPerformed(evt);
            }
        });

        jBtnConcluir.setText("Concluir");
        jBtnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConcluirActionPerformed(evt);
            }
        });

        jBtnCriarPlanilha.setText("Criar planilha");
        jBtnCriarPlanilha.setEnabled(false);
        jBtnCriarPlanilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCriarPlanilhaActionPerformed(evt);
            }
        });

        jBtnCopiar.setText("Copiar para a área de transferência");
        jBtnCopiar.setEnabled(false);
        jBtnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCopiarActionPerformed(evt);
            }
        });

        jLCopiado.setForeground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTfCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnCriarPlanilha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnCopiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLCopiado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnConcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jTfCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLErro)
                .addGap(18, 18, 18)
                .addComponent(jLCopiado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConcluir)
                    .addComponent(jBtnCriarPlanilha)
                    .addComponent(jBtnCopiar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setCaminho();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTfCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfCaminhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfCaminhoActionPerformed

    private void jBtnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConcluirActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnConcluirActionPerformed

    private void jBtnCriarPlanilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCriarPlanilhaActionPerformed
        String caminho = jTfCaminho.getText();
        
        if (new File(caminho).isFile()) {
            jLErro.setText("Insira um diretório");
            return;
        }

        criarArquivo(caminho);
    }//GEN-LAST:event_jBtnCriarPlanilhaActionPerformed

    private void jBtnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCopiarActionPerformed
        String caminho = jTfCaminho.getText();
        
        if (new File(caminho).isFile()) {
            jLErro.setText("Insira um diretório");
            return;
        }
        
        StringSelection selection = new StringSelection(caminho);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);
        
        jLCopiado.setText("Copiado!");
    }//GEN-LAST:event_jBtnCopiarActionPerformed

    public void setCaminho() {
        jFileChooser1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.showOpenDialog(null);
        
        File file = jFileChooser1.getSelectedFile();
        caminho = file.getPath();
        
        jTfCaminho.setText(caminho);
        verificarCaminho();
    }
    
    public void verificarCaminho() {
        if (jTfCaminho.getText().equals("")) {
            jLErro.setText("Preencha o campo de caminho do arquivo");
            return;
        }
        
        jBtnCriarPlanilha.setEnabled(true);
        jBtnCopiar.setEnabled(true);
    }
    
    public void criarArquivo(String caminho) {
        try {
            if (new File(caminho).isFile()) {
                return;
            }

            File file = new File(caminho + "\\arquivo.csv");
            file.getParentFile().mkdirs();
            file.createNewFile();
            
            FileWriter fileWriter = new FileWriter(file);
            BufferedWriter writer = new BufferedWriter(fileWriter);
            
            writer.write("Tipo;Valor;Data;Categoria;Saldo\n");
            
            writer.close();
            
        } catch (IOException ex) {
            Logger.getLogger(GerenciadorDados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarPlanilhaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarPlanilhaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarPlanilhaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarPlanilhaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CriarPlanilhaUI dialog = new CriarPlanilhaUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConcluir;
    private javax.swing.JButton jBtnCopiar;
    private javax.swing.JButton jBtnCriarPlanilha;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLCopiado;
    private javax.swing.JLabel jLErro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTfCaminho;
    // End of variables declaration//GEN-END:variables
}
